name: Windows CI

on:
  push:
    branches: [ main, master ]
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  hotpath:
    name: hotpath - build & test
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        run: choco install ninja --yes --no-progress
        shell: pwsh

      - name: Set up MSVC (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure hotpath
        run: |
          cmake -S hotpath -B build-hotpath ^
            -G "Ninja Multi-Config" ^
            -DDVREN_BUILD_TESTS=ON ^
            -DDVREN_BUILD_CPU=ON ^
            -DDVREN_BUILD_CUDA=OFF
        shell: pwsh

      - name: Build hotpath runner
        run: cmake --build build-hotpath --config $env:BUILD_TYPE --target hp_runner
        shell: pwsh

      - name: Run hotpath tests
        run: |
          Set-StrictMode -Version Latest
          .\build-hotpath\${{ env.BUILD_TYPE }}\hp_runner.exe | Tee-Object hp_runner.log
        shell: pwsh

  dvren:
    name: dvren - build & test
    runs-on: windows-latest
    needs: hotpath

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        run: choco install ninja --yes --no-progress
        shell: pwsh

      - name: Set up MSVC (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure dvren
        run: |
          cmake -S . -B build ^
            -G "Ninja Multi-Config" ^
            -DDVREN_ENABLE_CUDA=OFF ^
            -DDVREN_BUILD_PROJECT_TESTS=ON ^
            -DDVREN_ENABLE_HOTPATH_TESTS=OFF
        shell: pwsh

      - name: Build dvren targets
        run: cmake --build build --config $env:BUILD_TYPE --target dvren_core_tests dvren_render
        shell: pwsh

      - name: Run dvren tests
        run: ctest --output-on-failure --test-dir build -C $env:BUILD_TYPE
        shell: pwsh

      - name: Smoke CLI run
        run: |
          Set-StrictMode -Version Latest
          .\build\${{ env.BUILD_TYPE }}\dvren_render.exe examples\simple_volume.json ci_output.ppm
          Remove-Item ci_output.ppm
        shell: pwsh
